### ISSUE TITLE
Make variancechecker() less ugly

### ISSUE THREAD

**Issue by 2hands10fingers** [2hands10fingers/color-the-internet#1]
Currently the variancechecker() function is disgusting. Make it much more elegant and reduce line length. It can be found in packageparser.py

**Comment by CometS1** [comment]
I'll take a look at this

**Comment by CometS1** [comment]
Just a question, is elif i < 40 and i >= 35: suppose to give 4.0, not 3.5? Also. is elif i < 5 and i >= 0: suppose to give 15, not 0.5?

**Comment by CometS1** [comment]
@2hands10fingers Also, should 1000000 return 0.0095?

**Comment by 2hands10fingers** [comment]
@CometS1 Good catch on the elif i < 40. It seems I accidentally skipped a number. 

The elif i < 5 and i >= 0 is supposed to return 15, yes

**Comment by 2hands10fingers** [comment]
Issue is now closed. Thanks everyone for adding their entries. @CometS1 takes the cake for cleanest and most functional approach.
